services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - questdb
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - QDB_HTTP_HOST=${QDB_HTTP_HOST}
      - QDB_HTTP_PORT=${QDB_HTTP_PORT}
      - QDB_HTTP_USER=${QDB_HTTP_USER}
      - QDB_HTTP_PASSWORD=${QDB_HTTP_PASSWORD}
      - QDB_PG_HOST=${QDB_PG_HOST}
      - QDB_PG_PORT=${QDB_PG_PORT}
      - QDB_PG_USER=${QDB_PG_USER}
      - QDB_PG_PASSWORD=${QDB_PG_PASSWORD}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_API_KEY_FILENAME=${FIREBASE_API_KEY_FILENAME}
    restart: always
    networks:
      - fitapp-network

  postgres:
    image: postgres:14
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fitapp-network
    restart: always

  questdb:
    image: questdb/questdb:latest
    hostname: questdb
    container_name: questdb
    environment:
      - QDB_HTTP_USER=${QDB_HTTP_USER}
      - QDB_HTTP_PASSWORD=${QDB_HTTP_PASSWORD}
    ports:
      - "8812:8812"
      - "9000:9000"
    volumes:
      - questdb_data:/root/.questdb/db
    networks:
      - fitapp-network
    restart: always

networks:
  fitapp-network:
    driver: bridge

volumes:
  pgdata:
  questdb_data: